Repository EmbarkStudios/emote, pull requests merged in 2023-03, with the labels that each got.

#88 Use pdm-torch-plugin from PyPi
  .buildkite/install-repo.sh
  .buildkite/run-bandit.sh
  .buildkite/run-black.sh
  .buildkite/run-isort.sh
  .buildkite/validate-lockfile.sh
  pdm.lock
  plugins/pdm-plugin-torch/README.md
  plugins/pdm-plugin-torch/pyproject.toml
  plugins/pdm-plugin-torch/src/pdm_plugin_torch/__init__.py
  plugins/pdm-plugin-torch/src/pdm_plugin_torch/config.py
  plugins/pdm-plugin-torch/src/pdm_plugin_torch/main.py
  pyproject.toml
  torch.lock
Labels: a: ci, a: dependency

#87 Change minimal version to Python3.9
  .buildkite/Dockerfile
  .buildkite/build-ci-runner.sh
  .buildkite/pipeline.yml
  emote/proxies.py
  pdm.lock
  pyproject.toml
  tests/test_htm.py
  torch.lock
Labels: a: dependency

#90 use input_key in FeatureAgentProxy.input_names
  CHANGELOG.md
  emote/sac.py
  tests/test_sac.py
Labels: t: bug

#91 allow None in cycle to disable
  CHANGELOG.md
  emote/callback.py
  emote/trainer.py
  tests/test_trainer.py
Labels: t: bug

#95 Gym is replaced by gymnasium
  emote/callbacks.py
  emote/memory/builder.py
  experiments/gym/train_lunar_lander.py
  pdm.lock
  pyproject.toml
  tests/gym/dict_gym_wrapper.py
  tests/gym/hit_the_middle.py
  tests/test_htm.py
  tests/test_lunar_lander.py
  torch.lock
Labels: a: dependency

#103 fix tests
  tests/test_memory_logger.py
Labels: t: bug, a: test

#102 Updated a few things missed in 3.8=>3.9
  .github/workflows/docs.yml
  .github/workflows/pre-release.yaml
  README.md
Labels: t: documentation, a: ci

#107 Improve CI error messages
  .buildkite/run-bandit.sh
  .buildkite/run-black.sh
  .buildkite/run-isort.sh
Labels: a: ci

#101 Ali/mbrl lib
  emote/extra/schedules.py
  emote/memory/memory.py
  emote/memory/table.py
  emote/models/__init__.py
  emote/models/callbacks.py
  emote/models/ensemble.py
  emote/models/model.py
  emote/models/model_env.py
  emote/sac.py
  emote/typing.py
  emote/utils/math.py
  emote/utils/model.py
  experiments/gym/train_lunar_lander.py
  experiments/gym/train_lunar_lander_model_based.py
  tests/gym/dict_gym_wrapper.py
Labels: t: feature
