Repository EmbarkStudios/emote, pull requests merged in 2023-06, with the labels that each got.

#123 check for double-init episodes
  emote/memory/memory.py
  tests/test_memory_logger.py
Labels: trigger: cloud

#145 update pdm-plugin-torch
  pyproject.toml
Labels: t: bug, a: dependency

#146 updating the checkpointer and checkpoint loader
  emote/callback.py
  emote/callbacks/checkpointing.py
  emote/callbacks/loss.py
  emote/mixins/logging.py
  tests/test_checkpoints.py
Labels: t: feature
