Repository EmbarkStudios/emote, pull requests merged in 2023-08, with the labels that each got.

#161 Simona/onnx
  emote/extra/onnx_exporter.py
Labels: t: bug

#162 Simona/add conditions
  emote/nn/curl.py
  emote/sac.py
Labels: t: feature, t: bug

#165 simplify agent proxy setup
  emote/proxies.py
  emote/sac.py
  emote/utils/deprecated.py
Labels: trigger: cloud
